name: Tapmad Playlist BD

on:
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য
  workflow_call:     # Master Controller এর জন্য
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা পর পর অটো আপডেট হওয়ার জন্য

permissions:
  contents: write # Git Commit & Push করার পারমিশন

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      env:
        TAPMAD_API_URL: ${{ secrets.TAPMAD_API_URL }}
      run: python Script/Tapmad_bd.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # পরিবর্তন ট্র্যাক করা
        git add Tapmad.m3u
        
        # পরিবর্তন না থাকলে এরর না দিয়ে সহজে বের হয়ে যাওয়া
        git diff-index --quiet HEAD || git commit -m "Automated Tapmad Playlist Update"
        
        # rebase করে সেফ পুশ করা
        git pull --rebase origin main || true
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
